import {Bus} from '../js/bus.js';
import {PPU} from '../js/ppu.js';

// NMI is edge-triggered when VBlank and NMI-enable overlap.
const p=new PPU();
p.status|=0x80;p.cpuWrite(0,0x80);
if(!p.pollNmi()) throw new Error('NMI edge not generated by $2000 enable during VBlank');
if(p.pollNmi()) throw new Error('NMI edge repeated without new edge');
p.cpuRead(2);
if(p.nmiLine) throw new Error('$2002 did not lower NMI line');

// Sprite overflow bug approximation: after 8 in-range sprites, a later OAM byte may trip overflow.
const sp=new PPU();sp.ctrl=0;sp.mask=0x18;sp.beginSpriteEvaluation(20);
for(let i=0;i<8;i++){sp.oam[i*4]=19;sp.oam[i*4+1]=i;sp.oam[i*4+2]=0;sp.oam[i*4+3]=i*8}
sp.oam[8*4]=200;sp.oam[9*4]=19;
for(let i=0;i<64;i++)sp.stepSpriteEvaluation();
if(!(sp.status&0x20)) throw new Error('sprite overflow not set');
if(sp.nextScanlineSprites.length!==8) throw new Error('secondary OAM should retain eight sprites');

// DMC DMA uses the bus and consumes 4 CPU cycles before completing the read.
const b=new Bus();b.cart={cpuRead:a=>a===0xC123?0x5a:0, clockCpu:()=>false};
b.apu.dmc.fetchPending=true;b.apu.dmc.bytesRemaining=1;b.apu.dmc.currentAddress=0xC123;b.apu.dmc.irqEnabled=true;
if(!b.requestDmcDma(0xC123)) throw new Error('DMC DMA request rejected');
const before=b.cpu.totalCycles;
for(let i=0;i<12;i++)b.clock(); // four CPU slots at NTSC divider 3
if(b.dmcDma.active) throw new Error('DMC DMA did not complete');
if(b.cpu.totalCycles-before!==4) throw new Error('DMC DMA did not consume four CPU cycles');
if(b.apu.dmc.sampleBuffer!==0x5a||b.apu.dmc.sampleBufferEmpty) throw new Error('DMC DMA data not delivered');
if(!b.apu.dmcIrq) throw new Error('DMC terminal IRQ not raised');

const state=b.snapshotBinary({});
if(state.version!==37||!state.dmcDma) throw new Error('v36 state missing DMC DMA state');
console.log('OK v0.7.8 timing: NMI edge, sprite overflow, DMC DMA, state v37');
