const NTSC_CPU_HZ=1789773,PAL_CPU_HZ=1662607,DENDY_CPU_HZ=1773448;
const DMC_NTSC=[428,380,340,320,286,254,226,214,190,160,142,128,106,85,72,54];
const DMC_PAL=[398,354,316,298,276,236,210,198,176,148,132,118,98,78,66,50];
const LENGTH=[10,254,20,2,40,4,80,6,160,8,60,10,14,12,26,14,12,16,24,18,48,20,96,22,192,24,72,26,16,28,32,30];
const NOISE_NTSC=[4,8,16,32,64,96,128,160,202,254,380,508,762,1016,2034,4068];
const NOISE_PAL=[4,8,14,30,60,88,118,148,188,236,354,472,708,944,1890,3778];
const DUTY=[[0,1,0,0,0,0,0,0],[0,1,1,0,0,0,0,0],[0,1,1,1,1,0,0,0],[1,0,0,1,1,1,1,1]];
const TRI=[15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15];
function env(){return{start:false,divider:0,decay:0}}
export class APU{
 constructor(){this.enabled=true;this.latencyHint='balanced';this.ctx=null;this.node=null;this.master=null;this.status=0;this.regs=new Uint8Array(0x18);this.bus=null;this.cpuCycles=0;this.frameMode5=false;this.frameIrqInhibit=false;this.frameIrq=false;this.dmcIrq=false;this.pulse=[this.newPulse(),this.newPulse()];this.triangle={length:0,linear:0,reload:false,timer:0,seq:0};this.noise={length:0,envelope:env(),timer:0,lfsr:1};this.region='NTSC';this.cpuHz=NTSC_CPU_HZ;this.dmcRates=DMC_NTSC;this.noisePeriods=NOISE_NTSC;this.dmc={enabled:false,irqEnabled:false,loop:false,rate:DMC_NTSC[0],timer:DMC_NTSC[0],output:0,sampleAddress:0xc000,sampleLength:1,currentAddress:0xc000,bytesRemaining:0,sampleBuffer:0,sampleBufferEmpty:true,fetchPending:false,shift:0,bitsRemaining:8,silence:true};this.sampleRate=48000;this.sampleAcc=0;this.sampleBlock=new Float32Array(1024);this.samplePos=0;this.evenCycle=false;this.suppressOutput=false;this.audioBackend='worklet';this.fallbackQueue=[];this.fallbackOffset=0;this.audioStats={available:0,underruns:0,overruns:0,lastUnderruns:0};this.adaptiveLatency=true;this.statsTimer=0;this.targetBlockSize=1024}
 newPulse(){return{length:0,envelope:env(),sweepDivider:0,sweepReload:false,timer:0,seq:0}}
 connectBus(bus){this.bus=bus}
 setRegion(region){this.region=region==='PAL'?'PAL':region==='Dendy'?'Dendy':'NTSC';this.cpuHz=this.region==='PAL'?PAL_CPU_HZ:this.region==='Dendy'?DENDY_CPU_HZ:NTSC_CPU_HZ;this.dmcRates=this.region==='PAL'?DMC_PAL:DMC_NTSC;this.noisePeriods=this.region==='PAL'?NOISE_PAL:NOISE_NTSC;this.dmc.rate=this.dmcRates[this.regs[0x10]&15]||this.dmcRates[0]}
 async init(){if(this.ctx){if(this.ctx.state==='suspended')await this.ctx.resume();return}this.ctx=new (window.AudioContext||window.webkitAudioContext)({latencyHint:this.latencyHint||'balanced'});this.sampleRate=this.ctx.sampleRate||48000;this.master=this.ctx.createGain();this.master.gain.value=this.enabled?0.85:0;try{if(!this.ctx.audioWorklet||typeof AudioWorkletNode==='undefined')throw new Error('AudioWorklet indisponível');await this.ctx.audioWorklet.addModule('./js/apu-worklet.js');this.node=new AudioWorkletNode(this.ctx,'neo-nes-apu',{numberOfInputs:0,numberOfOutputs:1,outputChannelCount:[1]});this.audioBackend='worklet';this.node.port.onmessage=e=>{const d=e.data||{};if(d.type==='stats'){const prev=this.audioStats.underruns||0;this.audioStats={available:d.available||0,underruns:d.underruns||0,overruns:d.overruns||0,lastUnderruns:Math.max(0,(d.underruns||0)-prev)};if(this.adaptiveLatency)this.adaptAudioBuffer()}};this.node.connect(this.master).connect(this.ctx.destination)}catch(err){console.warn('AudioWorklet indisponível; usando fallback ScriptProcessor',err);this.audioBackend='script';this.fallbackQueue=[];const sp=this.ctx.createScriptProcessor(1024,0,1);sp.onaudioprocess=e=>{const out=e.outputBuffer.getChannelData(0);out.fill(0);let pos=0;while(pos<out.length&&this.fallbackQueue.length){const q=this.fallbackQueue[0],take=Math.min(out.length-pos,q.length-this.fallbackOffset);out.set(q.subarray(this.fallbackOffset,this.fallbackOffset+take),pos);pos+=take;this.fallbackOffset+=take;if(this.fallbackOffset>=q.length){this.fallbackQueue.shift();this.fallbackOffset=0}}};this.fallbackOffset=0;this.node=sp;sp.connect(this.master).connect(this.ctx.destination)}}
 restartDmc(){const d=this.dmc;d.currentAddress=d.sampleAddress;d.bytesRemaining=d.sampleLength}
 write(a,v){if(a<0x4000||a>0x4017)return;this.regs[a-0x4000]=v;
  if(a===0x4001)this.pulse[0].sweepReload=true;else if(a===0x4003){if(this.status&1)this.pulse[0].length=LENGTH[(v>>3)&31];this.pulse[0].envelope.start=true;this.pulse[0].seq=0}
  else if(a===0x4005)this.pulse[1].sweepReload=true;else if(a===0x4007){if(this.status&2)this.pulse[1].length=LENGTH[(v>>3)&31];this.pulse[1].envelope.start=true;this.pulse[1].seq=0}
  else if(a===0x400b){if(this.status&4)this.triangle.length=LENGTH[(v>>3)&31];this.triangle.reload=true}
  else if(a===0x400f){if(this.status&8)this.noise.length=LENGTH[(v>>3)&31];this.noise.envelope.start=true}
  else if(a===0x4010){const d=this.dmc;d.irqEnabled=!!(v&0x80);d.loop=!!(v&0x40);d.rate=this.dmcRates[v&15];if(!d.irqEnabled)this.dmcIrq=false}
  else if(a===0x4011)this.dmc.output=v&0x7f;else if(a===0x4012)this.dmc.sampleAddress=0xc000+((v&255)<<6);else if(a===0x4013)this.dmc.sampleLength=((v&255)<<4)+1;
  else if(a===0x4015){this.status=v&0x1f;if(!(v&1))this.pulse[0].length=0;if(!(v&2))this.pulse[1].length=0;if(!(v&4))this.triangle.length=0;if(!(v&8))this.noise.length=0;const d=this.dmc;d.enabled=!!(v&0x10);if(!d.enabled){d.bytesRemaining=0;d.fetchPending=false}else if(d.bytesRemaining===0)this.restartDmc();this.dmcIrq=false}
  else if(a===0x4017){this.frameMode5=!!(v&0x80);this.frameIrqInhibit=!!(v&0x40);if(this.frameIrqInhibit)this.frameIrq=false;this.cpuCycles=0;if(this.frameMode5){this.quarterFrame();this.halfFrame()}}
 }
 read(a){if(a===0x4015){let v=0;if(this.pulse[0].length)v|=1;if(this.pulse[1].length)v|=2;if(this.triangle.length)v|=4;if(this.noise.length)v|=8;if(this.dmc.bytesRemaining>0)v|=0x10;if(this.frameIrq)v|=0x40;if(this.dmcIrq)v|=0x80;this.frameIrq=false;return v}return 0}
 pulseTimer(i){const o=i?4:0;return this.regs[o+2]|((this.regs[o+3]&7)<<8)}
 setPulseTimer(i,t){const o=i?4:0;t=Math.max(0,Math.min(0x7ff,t|0));this.regs[o+2]=t&255;this.regs[o+3]=(this.regs[o+3]&0xf8)|((t>>8)&7)}
 envelopeVolume(regIndex,state){const r=this.regs[regIndex];return(r&0x10)?(r&15):state.envelope.decay}
 clockEnvelope(regIndex,state){const e=state.envelope,period=this.regs[regIndex]&15,loop=!!(this.regs[regIndex]&0x20);if(e.start){e.start=false;e.decay=15;e.divider=period}else if(e.divider===0){e.divider=period;if(e.decay>0)e.decay--;else if(loop)e.decay=15}else e.divider--}
 quarterFrame(){this.clockEnvelope(0,this.pulse[0]);this.clockEnvelope(4,this.pulse[1]);this.clockEnvelope(0x0c,this.noise);const control=!!(this.regs[8]&0x80),reload=this.regs[8]&0x7f;if(this.triangle.reload)this.triangle.linear=reload;else if(this.triangle.linear>0)this.triangle.linear--;if(!control)this.triangle.reload=false}
 sweepTarget(i){const r=this.regs[(i?4:0)+1],t=this.pulseTimer(i),delta=t>>(r&7);return(r&8)?t-delta-(i?0:1):t+delta}
 clockSweep(i){const o=i?4:0,r=this.regs[o+1],p=this.pulse[i],period=((r>>4)&7)+1,target=this.sweepTarget(i);if(p.sweepDivider===0&&(r&0x80)&&(r&7)&&this.pulseTimer(i)>=8&&target>=0&&target<=0x7ff)this.setPulseTimer(i,target);if(p.sweepDivider===0||p.sweepReload){p.sweepDivider=period;p.sweepReload=false}else p.sweepDivider--}
 halfFrame(){for(let i=0;i<2;i++){if(this.pulse[i].length&&!(this.regs[i?4:0]&0x20))this.pulse[i].length--;this.clockSweep(i)}if(this.triangle.length&&!(this.regs[8]&0x80))this.triangle.length--;if(this.noise.length&&!(this.regs[0x0c]&0x20))this.noise.length--}
 clockPulseTimers(){for(let i=0;i<2;i++){const p=this.pulse[i],period=this.pulseTimer(i);if(p.timer<=0){p.timer=period;p.seq=(p.seq+1)&7}else p.timer--}}
 clockTriangleTimer(){const t=this.regs[0x0a]|((this.regs[0x0b]&7)<<8);if(this.triangle.timer<=0){this.triangle.timer=t;if(this.triangle.length&&this.triangle.linear&&t>1)this.triangle.seq=(this.triangle.seq+1)&31}else this.triangle.timer--}
 clockNoiseTimer(){const n=this.noise,period=this.noisePeriods[this.regs[0x0e]&15];if(n.timer<=0){n.timer=period;const tap=(this.regs[0x0e]&0x80)?6:1,fb=(n.lfsr^(n.lfsr>>tap))&1;n.lfsr=(n.lfsr>>1)|(fb<<14)}else n.timer--}
 clockDmc(){const d=this.dmc;if(!d.enabled)return;if(d.sampleBufferEmpty&&!d.fetchPending&&d.bytesRemaining>0&&this.bus){if(this.bus.requestDmcDma?.(d.currentAddress)){d.fetchPending=true}}if(--d.timer<=0){d.timer=d.rate;if(!d.silence){if(d.shift&1){if(d.output<=125)d.output+=2}else if(d.output>=2)d.output-=2}d.shift>>=1;if(--d.bitsRemaining===0){d.bitsRemaining=8;if(d.sampleBufferEmpty)d.silence=true;else{d.silence=false;d.shift=d.sampleBuffer;d.sampleBufferEmpty=true}}}}

 completeDmcDma(data){const d=this.dmc;if(!d.fetchPending)return;d.sampleBuffer=data&255;d.sampleBufferEmpty=false;d.fetchPending=false;d.currentAddress=d.currentAddress===0xffff?0x8000:d.currentAddress+1;d.bytesRemaining--;if(d.bytesRemaining===0){if(d.loop)this.restartDmc();else if(d.irqEnabled)this.dmcIrq=true}}
 pulseOut(i){if(!(this.status&(1<<i)))return 0;const p=this.pulse[i],timer=this.pulseTimer(i),target=this.sweepTarget(i);if(!p.length||timer<8||target>0x7ff||target<0)return 0;const duty=(this.regs[i?4:0]>>6)&3;return DUTY[duty][p.seq]?this.envelopeVolume(i?4:0,p):0}
 triangleOut(){if(!(this.status&4)||!this.triangle.length||!this.triangle.linear)return 0;const t=this.regs[0x0a]|((this.regs[0x0b]&7)<<8);return t<2?0:TRI[this.triangle.seq]}
 noiseOut(){if(!(this.status&8)||!this.noise.length||(this.noise.lfsr&1))return 0;return this.envelopeVolume(0x0c,this.noise)}
 mixedSample(){const p1=this.pulseOut(0),p2=this.pulseOut(1),tri=this.triangleOut(),noi=this.noiseOut(),dmc=(this.status&0x10)?this.dmc.output:0;const ps=p1+p2;const pulse=ps?95.88/(8128/ps+100):0;const tnd=(tri||noi||dmc)?159.79/(1/(tri/8227+noi/12241+dmc/22638)+100):0;const expansion=this.bus?.cart?.expansionAudioSample?.()||0;return Math.max(-1,Math.min(1,(pulse+tnd)*1.30+expansion-.02))}
 pushSample(s){if(this.suppressOutput)return;if(this.sampleBlock.length!==this.targetBlockSize&&this.samplePos===0)this.sampleBlock=new Float32Array(this.targetBlockSize);this.sampleBlock[this.samplePos++]=s;if(this.samplePos===this.sampleBlock.length){if(this.node){const out=this.sampleBlock.slice();if(this.audioBackend==='worklet'&&this.node.port)this.node.port.postMessage({type:'samples',buffer:out.buffer},[out.buffer]);else if(this.audioBackend==='script'){this.fallbackQueue.push(out);if(this.fallbackQueue.length>12)this.fallbackQueue.shift()}}this.samplePos=0}}
 requestStats(){if(this.node&&this.audioBackend==='worklet'&&this.node.port)this.node.port.postMessage({type:'stats'})}
 adaptAudioBuffer(){const u=this.audioStats.lastUnderruns||0;if(u>128&&this.targetBlockSize<2048)this.targetBlockSize*=2;else if(u===0&&this.audioStats.available>this.sampleRate*.12&&this.targetBlockSize>512)this.targetBlockSize=Math.max(512,this.targetBlockSize>>1)}
 clock(){this.cpuCycles++;this.evenCycle=!this.evenCycle;this.clockTriangleTimer();if(this.evenCycle){this.clockPulseTimers();this.clockNoiseTimer()}this.clockDmc();const c=this.cpuCycles,pal=this.region==='PAL';const q1=pal?8313:7457,q2=pal?16627:14913,q3=pal?24939:22371,q4=pal?33252:29829,q5=pal?41565:37282;if(!this.frameMode5){if(c===q1||c===q3)this.quarterFrame();if(c===q2){this.quarterFrame();this.halfFrame()}if(c===q4){this.quarterFrame();this.halfFrame();if(!this.frameIrqInhibit)this.frameIrq=true}if(c>=q4+1)this.cpuCycles=0}else{if(c===q1||c===q3)this.quarterFrame();if(c===q2||c===q4){this.quarterFrame();this.halfFrame()}if(c>=q5)this.cpuCycles=0}this.sampleAcc+=this.sampleRate;if(this.sampleAcc>=this.cpuHz){this.sampleAcc-=this.cpuHz;this.pushSample(this.mixedSample())}return this.frameIrq||this.dmcIrq}
 setLatencyHint(v){this.adaptiveLatency=v==='auto';this.latencyHint=['interactive','balanced','playback'].includes(v)?v:'balanced';this.targetBlockSize=v==='interactive'?512:v==='playback'?2048:1024}
 setEnabled(v){this.enabled=v;if(this.master&&this.ctx)this.master.gain.setTargetAtTime(v?0.85:0,this.ctx.currentTime,.01)}
 captureFast(t={}){t.enabled=this.enabled;t.region=this.region;t.status=this.status;t.regs=t.regs instanceof Uint8Array?t.regs:new Uint8Array(this.regs.length);t.regs.set(this.regs);t.cpuCycles=this.cpuCycles;t.frameMode5=this.frameMode5;t.frameIrqInhibit=this.frameIrqInhibit;t.frameIrq=this.frameIrq;t.dmcIrq=this.dmcIrq;t.sampleAcc=this.sampleAcc;t.evenCycle=this.evenCycle;t.pulse=this.pulse.map(x=>({...x,envelope:{...x.envelope}}));t.triangle={...this.triangle};t.noise={...this.noise,envelope:{...this.noise.envelope}};t.dmc={...this.dmc};return t}
 snapshot(){return{enabled:this.enabled,region:this.region,status:this.status,regs:Array.from(this.regs),cpuCycles:this.cpuCycles,frameMode5:this.frameMode5,frameIrqInhibit:this.frameIrqInhibit,frameIrq:this.frameIrq,dmcIrq:this.dmcIrq,sampleAcc:this.sampleAcc,evenCycle:this.evenCycle,pulse:this.pulse.map(x=>({...x,envelope:{...x.envelope}})),triangle:{...this.triangle},noise:{...this.noise,envelope:{...this.noise.envelope}},dmc:{...this.dmc}}}
 restoreFast(s){if(!s)return;this.enabled=s.enabled!==false;if(s.region)this.setRegion(s.region);this.status=s.status||0;this.regs.set(s.regs||[]);this.cpuCycles=s.cpuCycles||0;this.frameMode5=!!s.frameMode5;this.frameIrqInhibit=!!s.frameIrqInhibit;this.frameIrq=!!s.frameIrq;this.dmcIrq=!!s.dmcIrq;this.sampleAcc=s.sampleAcc||0;this.evenCycle=!!s.evenCycle;if(s.pulse)this.pulse=s.pulse.map(x=>({...x,envelope:{...x.envelope}}));if(s.triangle)this.triangle={...s.triangle};if(s.noise)this.noise={...s.noise,envelope:{...s.noise.envelope}};if(s.dmc)Object.assign(this.dmc,s.dmc);if(this.master&&this.ctx)this.master.gain.setTargetAtTime(this.enabled?0.85:0,this.ctx.currentTime,.01)}

 restore(s){if(!s)return;this.enabled=s.enabled!==false;if(s.region)this.setRegion(s.region);this.status=s.status||0;this.regs.set(s.regs||[]);this.cpuCycles=s.cpuCycles||0;this.frameMode5=!!s.frameMode5;this.frameIrqInhibit=!!s.frameIrqInhibit;this.frameIrq=!!s.frameIrq;this.dmcIrq=!!s.dmcIrq;this.sampleAcc=s.sampleAcc||0;this.evenCycle=!!s.evenCycle;if(s.pulse)this.pulse=s.pulse.map(x=>({...x,envelope:{...x.envelope}}));if(s.triangle)this.triangle={...s.triangle};if(s.noise)this.noise={...s.noise,envelope:{...s.noise.envelope}};if(s.dmc)Object.assign(this.dmc,s.dmc);if(this.node&&this.audioBackend==='worklet'&&this.node.port)this.node.port.postMessage({type:'flush'});else if(this.audioBackend==='script'){this.fallbackQueue.length=0;this.fallbackOffset=0};if(this.master&&this.ctx)this.master.gain.setTargetAtTime(this.enabled?0.85:0,this.ctx.currentTime,.01)}
}
