import {CPU6502} from './cpu6502.js';import {PPU} from './ppu.js';import {APU} from './apu.js';import {InputHub} from './input-devices.js';

 function stateIntegrity(s){let h=2166136261>>>0;const mix=v=>{h^=(v&255);h=Math.imul(h,16777619)>>>0};const arr=a=>{if(!a)return;for(let i=0;i<a.length;i++)mix(a[i])};arr(s.ram);arr(s.ppu?.vram);arr(s.ppu?.palette);arr(s.ppu?.oam);arr(s.ppu?.secondaryOam);arr(s.cart?.prgRam);for(const v of [s.systemClock||0,s.cpuPhase||0,s.openBus||0,s.cpu?.pc||0,s.cpu?.a||0,s.cpu?.x||0,s.cpu?.y||0,s.ppu?.scanline||0,s.ppu?.cycle||0]){mix(v);mix(v>>>8);mix(v>>>16);mix(v>>>24)}return h.toString(16).padStart(8,'0')}

export class Bus{
 constructor(){this.debugger=null;this.ram=new Uint8Array(2048);this.cheats=[];this.cart=null;this.ppu=new PPU();this.apu=new APU();this.input=new InputHub();this.controller=this.input.controllers[0];this.controller2=this.input.controllers[1];this.controller3=this.input.controllers[2];this.controller4=this.input.controllers[3];this.cpu=new CPU6502(this);this.apu.connectBus(this);this.systemClock=0;this.cpuPhase=0;this.cpuDivider=3;this.openBus=0;this.dma={active:false,page:0,addr:0,data:0,dummy:true};this.dmcDma={active:false,address:0,remaining:0,deferred:0,collisions:0}}
 insertCartridge(c){this.cart=c;this.ppu.connectCartridge(c);this.setRegion(c?.region||'NTSC')}
 setRegion(region){this.region=region==='PAL'?'PAL':region==='Dendy'?'Dendy':'NTSC';this.cpuDivider=this.region==='PAL'?3.2:3;this.cpuPhase=0;this.ppu.setRegion(this.region);this.apu.setRegion(this.region)}
 setDebugger(d){this.debugger=d||null}
 peek(a){a&=0xffff;if(a<0x2000)return this.ram[a&0x7ff];if((this.cart?.format==='FDS'&&a>=0x4020)||(this.cart?.mapper===19&&a>=0x4800)){const v=this.cart.cpuRead(a);return v==null?this.openBus:(v&255)}if(a>=0x6000){const v=this.cart?.cpuRead(a);return v==null?this.openBus:(v&255)}return this.openBus&255}
  read(a){a&=0xffff;let v=this.openBus;if(a<0x2000)v=this.ram[a&0x7ff];else if(a<0x4000)v=this.ppu.cpuRead(a&7);else if(a===0x4015)v=this.apu.read(a);else if(a===0x4016)v=(this.openBus&0xe0)|(this.input.read4016()&1);else if(a===0x4017){const iv=this.input.read4017(this.ppu);v=this.input.port2Device==='zapper'&&!this.input.fourScore.enabled?((this.openBus&0xe0)|(iv&0x18)):((this.openBus&0xe0)|(iv&1));}else if((this.cart?.format==='FDS'&&a>=0x4020)||(this.cart?.mapper===19&&a>=0x4800)){v=this.cart.cpuRead(a);if(v==null)v=this.openBus;}else if(a>=0x6000){v=this.cart?.cpuRead(a);if(v==null)v=this.openBus;else if(a>=0x8000&&this.cheats.length){for(const c of this.cheats){if(c.enabled!==false&&c.address===a&&(c.compare==null||c.compare===v)){v=c.value&255;break}}}}this.openBus=v&255;this.debugger?.onMemoryAccess?.('read',a,this.openBus);return this.openBus}
  write(a,v){a&=0xffff;v&=255;this.openBus=v;this.debugger?.onMemoryAccess?.('write',a,v);if(a<0x2000)this.ram[a&0x7ff]=v;else if(a<0x4000)this.ppu.cpuWrite(a&7,v);else if(a===0x4014){this.dma.active=true;this.dma.page=v;this.dma.addr=0;this.dma.data=0;this.dma.dummy=true}else if(a===0x4016){this.input.write4016(v)}else if(a>=0x4000&&a<=0x4017)this.apu.write(a,v);else if(a>=0x4020)this.cart?.cpuWrite(a,v,this.cpu.totalCycles)}
 setCheats(list){this.cheats=Array.isArray(list)?list.map(c=>({...c})):[]}
 reset(){this.cpu.reset();this.ppu.scanline=0;this.ppu.cycle=0;this.ppu.frameComplete=false;this.ppu.status&=~0x80;this.systemClock=0;this.cpuPhase=0;this.cpuDivider=this.region==='PAL'?3.2:3;this.openBus=0;this.dma={active:false,page:0,addr:0,data:0,dummy:true};this.dmcDma={active:false,address:0,remaining:0,deferred:0,collisions:0}}
 requestDmcDma(address){if(this.dmcDma.active)return false;this.dmcDma.active=true;this.dmcDma.address=address&0xffff;this.dmcDma.remaining=4;this.dmcDma.deferred=0;return true}
 clockDmcDma(){const d=this.dmcDma;if(!d.active)return;if(--d.remaining<=0){const data=this.read(d.address);d.active=false;d.remaining=0;this.apu.completeDmcDma?.(data)}this.cpu.totalCycles++}
 clock(){const dbg=this.debugger?.enabled?this.debugger:null,oldSprite0=dbg?(this.ppu.status&0x40):0;this.ppu.clock();if(dbg&&!oldSprite0&&(this.ppu.status&0x40))dbg.onEvent?.('sprite0',`${this.ppu.scanline}:${this.ppu.cycle}`);this.cpuPhase+=1;if(this.cpuPhase+1e-9>=this.cpuDivider){this.cpuPhase-=this.cpuDivider;if(this.apu.clock())this.cpu.irqPending=true;if(this.cart?.clockCpu?.())this.cpu.irqPending=true;if(this.dmcDma.active){const oamWrite=this.dma.active&&!this.dma.dummy&&((this.cpu.totalCycles&1)===1);if(oamWrite){this.dmcDma.deferred++;this.dmcDma.collisions++;this.clockDma()}else this.clockDmcDma()}else if(this.dma.active)this.clockDma();else this.cpu.clock()}if(this.ppu.pollNmi?.()){this.cpu.nmiPending=true;dbg?.onEvent?.('nmi')}else if(this.ppu.nmi){this.ppu.nmi=false;this.cpu.nmiPending=true;dbg?.onEvent?.('nmi')}if(this.ppu.irq){this.ppu.irq=false;this.cpu.irqPending=true;dbg?.onEvent?.('irq','PPU/mapper')}this.systemClock++}
 clockDma(){const d=this.dma;if(d.dummy){if((this.cpu.totalCycles&1)===1){d.dummy=false;this.cpu.totalCycles++}else this.cpu.totalCycles++;return}if((this.cpu.totalCycles&1)===0){d.data=this.read((d.page<<8)|d.addr)}else{this.ppu.oam[(this.ppu.oamAddr+d.addr)&255]=d.data;d.addr=(d.addr+1)&255;if(d.addr===0){d.active=false;d.dummy=true}}this.cpu.totalCycles++}
 captureFast(t={}){t.format='NEO-NES-REWIND';t.version=37;t.ram=t.ram instanceof Uint8Array?t.ram:new Uint8Array(this.ram.length);t.ram.set(this.ram);t.systemClock=this.systemClock;t.cpuPhase=this.cpuPhase;t.region=this.region;t.openBus=this.openBus;t.cpu=this.cpu.snapshot();t.ppu=this.ppu.captureFast(t.ppu);t.cart=this.cart?.captureFast?.(t.cart)||null;t.apu=this.apu.captureFast(t.apu);t.dma={...this.dma};t.dmcDma={...this.dmcDma};t.controllers=this.input.controllers.map(c=>c.snapshotRuntime());t.input=this.input.snapshot();return t}
 restoreFast(s){if(!s||s.format!=='NEO-NES-REWIND')throw new Error('Rewind inválido');this.ram.set(s.ram);this.systemClock=s.systemClock||0;if(s.region)this.setRegion(s.region);this.cpuPhase=s.cpuPhase||0;this.openBus=s.openBus||0;this.cpu.restore(s.cpu);this.ppu.restore(s.ppu);this.cart?.restore?.(s.cart);(this.apu.restoreFast?this.apu.restoreFast(s.apu):this.apu.restore(s.apu));this.dma=s.dma?{...s.dma}:{active:false,page:0,addr:0,data:0,dummy:true};this.dmcDma=s.dmcDma?{...s.dmcDma}:{active:false,address:0,remaining:0};if(s.input)this.input.restore(s.input);else if(s.controllers)s.controllers.forEach((v,i)=>this.input.controllers[i]?.restoreRuntime(v))}
 snapshotBinary(t={}){t.format='NEO-NES-STATE';t.version=37;t.ram=t.ram instanceof Uint8Array?t.ram:new Uint8Array(this.ram.length);t.ram.set(this.ram);t.systemClock=this.systemClock;t.cpuPhase=this.cpuPhase;t.region=this.region;t.openBus=this.openBus;t.cpu=this.cpu.snapshot();t.ppu=this.ppu.captureFast(t.ppu);t.cart=this.cart?.captureFast?.(t.cart)||null;t.apu=this.apu.captureFast(t.apu);t.dma={...this.dma};t.dmcDma={...this.dmcDma};t.controllers=this.input.controllers.map(c=>c.snapshotRuntime());t.input=this.input.snapshot();t.integrity=stateIntegrity(t);return t}
 snapshot(){return {format:'NEO-NES-STATE',version:37,ram:Array.from(this.ram),systemClock:this.systemClock,cpuPhase:this.cpuPhase,region:this.region,openBus:this.openBus,cpu:this.cpu.snapshot(),ppu:this.ppu.snapshot(),cart:this.cart?.snapshot?.()||null,apu:this.apu.snapshot(),dma:{...this.dma},dmcDma:{...this.dmcDma},controllers:this.input.controllers.map(c=>c.snapshotRuntime()),input:this.input.snapshot()}}
 restore(s){if(!s||s.format!=='NEO-NES-STATE'||!s.ram||!s.version||s.version<5)throw new Error('Save state inválido ou antigo demais para esta versão');if(s.version>=32&&s.integrity&&stateIntegrity(s)!==s.integrity)throw new Error('Save state corrompido (integridade inválida)');this.ram.set(s.ram);this.systemClock=s.systemClock||0;if(s.region)this.setRegion(s.region);this.cpuPhase=s.cpuPhase||0;this.openBus=s.openBus||0;this.cpu.restore(s.cpu);this.ppu.restore(s.ppu);this.cart?.restore?.(s.cart);this.apu.restore(s.apu);this.dma=s.dma?{...s.dma}:{active:false,page:0,addr:0,data:0,dummy:true};this.dmcDma=s.dmcDma?{...s.dmcDma}:{active:false,address:0,remaining:0};if(s.input)this.input.restore(s.input);else if(s.controllers)s.controllers.forEach((v,i)=>this.input.controllers[i]?.restoreRuntime(v))}
}
