const dec=new TextDecoder('latin1');
const u16=(a,o)=>a[o]|(a[o+1]<<8);const u32=(a,o)=>(a[o]|(a[o+1]<<8)|(a[o+2]<<16)|(a[o+3]<<24))>>>0;
const zstr=a=>{let e=a.indexOf(0);if(e<0)e=a.length;return dec.decode(a.slice(0,e)).trim()};
export function parseNsf(buffer){const b=new Uint8Array(buffer);if(b.length<16)throw new Error('Arquivo NSF/NSFe muito pequeno');
 if(b[0]===0x4e&&b[1]===0x45&&b[2]===0x53&&b[3]===0x4d&&b[4]===0x1a){if(b.length<0x80)throw new Error('Cabeçalho NSF incompleto');const bank=Array.from(b.slice(0x70,0x78));return{format:'NSF',version:b[5],songs:b[6]||1,startSong:Math.max(1,b[7]||1),load:u16(b,8),init:u16(b,10),play:u16(b,12),title:zstr(b.slice(0x0e,0x2e)),artist:zstr(b.slice(0x2e,0x4e)),copyright:zstr(b.slice(0x4e,0x6e)),ntscSpeed:u16(b,0x6e)||16639,palSpeed:u16(b,0x78)||19997,region:b[0x7a],expansion:b[0x7b],bank,data:b.slice(0x80),labels:[],times:[],fades:[]}}
 if(b[0]===0x4e&&b[1]===0x53&&b[2]===0x46&&b[3]===0x45){let p=4,info=null,data=null,bank=new Array(8).fill(0),auth=[],labels=[],times=[],fades=[];while(p+8<=b.length){const size=u32(b,p),id=dec.decode(b.slice(p+4,p+8));p+=8;if(p+size>b.length)throw new Error(`Chunk NSFe ${id} truncado`);const c=b.slice(p,p+size);p+=size;if(id==='INFO'){if(c.length<10)throw new Error('INFO NSFe inválido');info={load:u16(c,0),init:u16(c,2),play:u16(c,4),region:c[6],expansion:c[7],songs:c[8]||1,startSong:(c[9]||0)+1}}else if(id==='DATA')data=c;else if(id==='BANK')bank=Array.from(c.slice(0,8));else if(id==='auth')auth=dec.decode(c).split('\0');else if(id==='tlbl')labels=dec.decode(c).split('\0').filter(Boolean);else if(id==='time')for(let i=0;i+3<c.length;i+=4)times.push((u32(c,i)|0));else if(id==='fade')for(let i=0;i+3<c.length;i+=4)fades.push((u32(c,i)|0));else if(id==='NEND')break}if(!info||!data)throw new Error('NSFe sem INFO/DATA');return{format:'NSFe',version:2,...info,title:auth[0]||'',artist:auth[1]||'',copyright:auth[2]||'',ripper:auth[3]||'',ntscSpeed:16639,palSpeed:19997,bank,data,labels,times,fades}}
 throw new Error('Formato de música não reconhecido');}

class NsfCart{
 constructor(doc){this.doc=doc;this.mapper=-1;this.submapper=0;this.nes2=false;this.hasTrainer=false;this.prg=doc.data;this.prgRamSize=0x2000;this.prgNvRamSize=0;this.region=((doc.region&3)===1)?'PAL':'NTSC';this.mirroring='horizontal';this.battery=false;this.prgRam=new Uint8Array(0x2000);this.chr=new Uint8Array(0x2000);this.chrRam=true;this.bankRegs=Uint8Array.from(doc.bank||[]);this.banked=this.bankRegs.some(Boolean);this.mem=new Uint8Array(65536);if(!this.banked){for(let i=0;i<doc.data.length&&doc.load+i<65536;i++)this.mem[doc.load+i]=doc.data[i]}else{const off=doc.load&0xfff,total=off+doc.data.length,n=Math.max(1,Math.ceil(total/0x1000));this.banks=Array.from({length:n},(_,i)=>new Uint8Array(0x1000));for(let i=0;i<doc.data.length;i++){const k=off+i,bi=k>>12,bo=k&0xfff;if(this.banks[bi])this.banks[bi][bo]=doc.data[i]}}
 }
 getMirroring(){return this.mirroring} ppuRead(a){return this.chr[a&0x1fff]} ppuWrite(a,v){this.chr[a&0x1fff]=v&255}
 cpuRead(a){a&=0xffff;if(a>=0x6000&&a<0x8000)return this.prgRam[a-0x6000];if(!this.banked)return this.mem[a];if(a>=0x8000){const slot=(a-0x8000)>>12,bank=this.bankRegs[slot]%(this.banks?.length||1);return this.banks?.[bank]?.[a&0xfff]??0}return 0}
 cpuWrite(a,v){a&=0xffff;v&=255;if(a>=0x5ff8&&a<=0x5fff&&this.banked){this.bankRegs[a-0x5ff8]=v;return}if(a>=0x6000&&a<0x8000)this.prgRam[a-0x6000]=v}
 snapshot(){return{bankRegs:Array.from(this.bankRegs),prgRam:Array.from(this.prgRam)}} restore(s){if(!s)return;this.bankRegs.set(s.bankRegs||[]);this.prgRam.set(s.prgRam||[])} captureFast(t={}){t.bankRegs=t.bankRegs instanceof Uint8Array?t.bankRegs:new Uint8Array(8);t.bankRegs.set(this.bankRegs);t.prgRam=t.prgRam instanceof Uint8Array?t.prgRam:new Uint8Array(this.prgRam.length);t.prgRam.set(this.prgRam);return t}
}

export class NsfPlayer{
 constructor(bus,doc){this.bus=bus;this.doc=doc;this.cart=new NsfCart(doc);this.song=Math.max(0,Math.min(doc.songs-1,(doc.startSong||1)-1));this.sentinel=0x07f0;this.nextPlayCycle=0;this.started=false;this.trackStartedAt=0;this.expansionUnsupported=[];const names=['VRC6','VRC7','FDS','MMC5','Namco 163','Sunsoft 5B'];for(let i=0;i<6;i++)if(doc.expansion&(1<<i))this.expansionUnsupported.push(names[i])}
 install(){this.bus.insertCartridge(this.cart);this.bus.reset();this.bus.ram[this.sentinel&0x7ff]=0x4c;this.bus.ram[(this.sentinel+1)&0x7ff]=this.sentinel&255;this.bus.ram[(this.sentinel+2)&0x7ff]=this.sentinel>>8;this.select(this.song);this.started=true}
 invoke(addr,a=0,x=0){const c=this.bus.cpu;c.a=a&255;c.x=x&255;c.y=0;c.p=0x24;c.sp=0xfd;c.jammed=false;c.cycles=0;c.pc=addr&0xffff;c.push(((this.sentinel-1)>>8)&255);c.push((this.sentinel-1)&255);let guard=0;while(!(c.pc===this.sentinel&&c.cycles===0)&&guard++<400000)this.bus.clock();if(guard>=400000)throw new Error('NSF: rotina não retornou (watchdog)')}
 select(index){this.song=Math.max(0,Math.min(this.doc.songs-1,index|0));this.bus.ram.fill(0);this.bus.ram[this.sentinel&0x7ff]=0x4c;this.bus.ram[(this.sentinel+1)&0x7ff]=this.sentinel&255;this.bus.ram[(this.sentinel+2)&0x7ff]=this.sentinel>>8;this.cart.prgRam.fill(0);this.cart.bankRegs.set(this.doc.bank||[]);this.bus.apu.reset?.();this.invoke(this.doc.init,this.song,this.cart.region==='PAL'?1:0);this.nextPlayCycle=this.bus.cpu.totalCycles+this.playPeriodCycles();this.trackStartedAt=performance.now();return this.song}
 playPeriodCycles(){const us=this.cart.region==='PAL'?(this.doc.palSpeed||19997):(this.doc.ntscSpeed||16639);const hz=this.cart.region==='PAL'?1662607:1789773;return Math.max(1,Math.round(hz*us/1e6))}
 runMs(ms){if(!this.started)return;const hz=this.cart.region==='PAL'?1662607:1789773,target=this.bus.cpu.totalCycles+Math.max(1,Math.round(hz*ms/1000));let guard=0;while(this.bus.cpu.totalCycles<target&&guard++<800000){if(this.bus.cpu.totalCycles>=this.nextPlayCycle&&this.bus.cpu.pc===this.sentinel&&this.bus.cpu.cycles===0){this.invoke(this.doc.play,0,0);this.nextPlayCycle+=this.playPeriodCycles()}else this.bus.clock()}if(guard>=800000)throw new Error('NSF: limite de execução excedido')}
 next(){return this.select((this.song+1)%this.doc.songs)} prev(){return this.select((this.song-1+this.doc.songs)%this.doc.songs)}
 label(){return this.doc.labels?.[this.song]||`Faixa ${this.song+1}`}
}
