const rgba=(n)=>[(n)&255,(n>>8)&255,(n>>16)&255,255];
function put(canvas,w,h,pixels,scale=1){canvas.width=w;canvas.height=h;const c=canvas.getContext('2d');const im=c.createImageData(w,h);for(let i=0,j=0;i<pixels.length;i++,j+=4){const q=rgba(pixels[i]);im.data[j]=q[0];im.data[j+1]=q[1];im.data[j+2]=q[2];im.data[j+3]=255}c.putImageData(im,0,0);canvas.style.imageRendering='pixelated'}
function color(ppu,index){return ppu.rgb(ppu.ppuPeek(0x3f00+(index&31)))}
export class PPUViewer{
 constructor(bus){this.bus=bus}
 patternTable(canvas,table=0,palette=0){const p=this.bus.ppu,out=new Uint32Array(128*128),base=(table&1)*0x1000;for(let tile=0;tile<256;tile++){const tx=(tile&15)*8,ty=(tile>>4)*8;for(let row=0;row<8;row++){const lo=p.ppuPeek(base+tile*16+row),hi=p.ppuPeek(base+tile*16+row+8);for(let col=0;col<8;col++){const bit=7-col,px=((lo>>bit)&1)|(((hi>>bit)&1)<<1);out[(ty+row)*128+tx+col]=color(p,(palette*4)+px)}}}put(canvas,128,128,out)}
 nametable(canvas,table=0){const p=this.bus.ppu,out=new Uint32Array(256*240),base=0x2000+((table&3)*0x400),pat=(p.ctrl&0x10)?0x1000:0;for(let ty=0;ty<30;ty++)for(let tx=0;tx<32;tx++){const tile=p.ppuPeek(base+ty*32+tx),at=p.ppuPeek(base+0x3c0+((ty>>2)*8)+(tx>>2)),shift=((ty&2)?4:0)+((tx&2)?2:0),pal=(at>>shift)&3;for(let row=0;row<8;row++){const lo=p.ppuPeek(pat+tile*16+row),hi=p.ppuPeek(pat+tile*16+row+8);for(let col=0;col<8;col++){const bit=7-col,px=((lo>>bit)&1)|(((hi>>bit)&1)<<1);out[(ty*8+row)*256+tx*8+col]=color(p,pal*4+px)}}}put(canvas,256,240,out)}
 palette(canvas){const p=this.bus.ppu,w=128,h=32,out=new Uint32Array(w*h);for(let i=0;i<32;i++){const c=p.rgb(p.ppuPeek(0x3f00+i)),x=(i%16)*8,y=(i>>4)*16;for(let yy=0;yy<16;yy++)for(let xx=0;xx<8;xx++)out[(y+yy)*w+x+xx]=c}put(canvas,w,h,out)}
 oam(canvas){const p=this.bus.ppu,w=256,h=256,out=new Uint32Array(w*h),sprH=(p.ctrl&0x20)?16:8;out.fill(0xff101018);for(let i=0;i<64;i++){const o=i*4,sy=(p.oam[o]+1)&255,tile=p.oam[o+1],attr=p.oam[o+2],sx=p.oam[o+3];for(let row=0;row<sprH;row++){let rr=(attr&0x80)?sprH-1-row:row,pt,ti,fy;if(sprH===16){pt=(tile&1)*0x1000;ti=tile&0xfe;if(rr>=8){ti++;fy=rr-8}else fy=rr}else{pt=(p.ctrl&0x08)?0x1000:0;ti=tile;fy=rr}const lo=p.ppuPeek(pt+ti*16+fy),hi=p.ppuPeek(pt+ti*16+fy+8);for(let col=0;col<8;col++){const bit=(attr&0x40)?col:7-col,px=((lo>>bit)&1)|(((hi>>bit)&1)<<1);if(!px)continue;const x=sx+col,y=sy+row;if(x<256&&y<240)out[y*w+x]=p.rgb(p.ppuPeek(0x3f10+((attr&3)<<2)+px))}}}put(canvas,w,h,out)}
 refresh(root=document){if(!this.bus.cart)return false;this.patternTable(root.querySelector('#patternTable0'),0,0);this.patternTable(root.querySelector('#patternTable1'),1,0);this.nametable(root.querySelector('#nametableViewer'),0);this.palette(root.querySelector('#paletteViewer'));this.oam(root.querySelector('#oamViewer'));return true}
}
